# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-a7W1CrkBPPDilKTX4fvYD0_lQB0wMEt
"""

model_json = model.to_json ()                   #indent=-2
with open (" final_model. json", "w") as json_file:
json_tile.write(model_json)

# serialize weights to H5
model.save_weights (" final_model . h5")
print("Saved mode l to di sk")